### ISSUE TITLE
The extending styles is not working

### ISSUE THREAD

**Issue by co-kevin** [pxmage/react-native-styled-px2dp#1]
```jsx
import { View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import getFlexibleStyled from 'react-native-styled-px2dp';

const { styled } = getFlexibleStyled({
  designWidth: 400,
  designHeight: 640,
});

// it works
const StyledView = styled.View`
    width: 100px;
`

// it not works
const StyledLinearGradient = styled(LinearGradient)`
    width: 100px;
`
```

**Comment by pxmage** [comment]
@hookszhang nice catch!
I didn't consider the situation when using extending styles.
I'll see if I could support it or find a workaround for you.

Thanks for submitting the issue  :)

**Comment by pxmage** [comment]
@hookszhang 
It should now work, I have published a new version onto npm.
 `react-native-styled-px2dp@1.1.2`

I've tested in my personal project, if something still go wrong, just let me know :)

**Comment by co-kevin** [comment]
Awesome!! 
It works for me. Thank you for your response.

**Comment by pxmage** [comment]
@hookszhang I'm glad that this lib helps you a bit :)
